baseURL = 'https://gwenfron.co.uk/'
locale = 'en-us'
title = 'Gwenfron'
theme = 'PaperMod'

[params]
description = 'Notes, updates, photos, and writing from Gwenfron.'

[params.label]
text = 'Home'

[markup]
	[markup.highlight]
		noClasses = false
